import { EventsDto, EVENT_FORMAT, EVENT_STATUS, EVENT_VISIBILITY, SCHEDULE_MODE, RECURRENCE_PATTERN, DETAIL_VIEW_MODE, REFUND_STRATEGY } from "../types"

export const mockEvents: EventsDto[] = [
  {
    title: "Tech Conference 2024",
    description: "Join us for the biggest tech conference of the year featuring industry leaders and cutting-edge innovations.",
    slug: "tech-conference-2024",
    avatar: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400",
    category: "technology",
    images: ["https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400"],
    tags: ["technology", "conference", "networking", "innovation"],
    status: EVENT_STATUS.PUBLISHED,
    creator: "user-1",
    host: "user-1",
    property: "property-1",
    schedule: {
      mode: SCHEDULE_MODE.SINGLE,
      start_time: new Date("2024-06-15T09:00:00Z"),
      end_time: new Date("2024-06-15T17:00:00Z"),
      registration_start_time: new Date("2024-05-01T00:00:00Z"),
      registration_end_time: new Date("2024-06-10T23:59:59Z"),
      timezone: "America/New_York",
      recurrence: {
        pattern: RECURRENCE_PATTERN.DAILY,
        interval: 1,
        current_occurences: 0,
        max_occurences: 1,
      },
    },
    visibility: EVENT_VISIBILITY.PUBLIC,
    ticketing: {
      enabled: true,
      capacity: 500,
    },
    hosting: {
      format: EVENT_FORMAT.PHYSICAL,
      address: {
        street: "123 Tech Street",
        city: "San Francisco",
        state: "CA",
        postal_code: "94105",
        country: "US",
        vanue: "Tech Convention Center",
        maps_link: "",
        nearby_landmark: "Near Golden Gate Bridge",
        instruction: "Enter through main entrance",
      },
      virtual_links: {},
    },
    access_control: {
      require_rsvp: true,
      view_details: DETAIL_VIEW_MODE.BEFORE,
    },
    cancellation_policy: {
      allowed: true,
      refund_strategy: REFUND_STRATEGY.PARTIAL,
      refund_percentage: 80,
      tiered_refunds: [],
    },
    terms_and_conditions: ["Standard terms apply"],
    sponsors: [
      { name: "TechCorp", image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=100" },
      { name: "InnovateLab" }
    ],
  },
  {
    title: "Virtual Music Festival",
    description: "Experience amazing music from the comfort of your home with our virtual music festival.",
    slug: "virtual-music-festival",
    avatar: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400",
    category: "music",
    images: [],
    tags: ["music", "virtual", "festival", "entertainment"],
    status: EVENT_STATUS.PUBLISHED,
    creator: "user-2",
    host: "user-2",
    property: "property-2",
    schedule: {
      mode: SCHEDULE_MODE.SINGLE,
      start_time: new Date("2024-07-20T19:00:00Z"),
      end_time: new Date("2024-07-20T23:00:00Z"),
      registration_start_time: new Date("2024-06-01T00:00:00Z"),
      registration_end_time: new Date("2024-07-19T23:59:59Z"),
      timezone: "UTC",
      recurrence: {
        pattern: RECURRENCE_PATTERN.DAILY,
        interval: 1,
        current_occurences: 0,
        max_occurences: 1,
      },
    },
    visibility: EVENT_VISIBILITY.PUBLIC,
    ticketing: {
      enabled: false,
      capacity: 1000,
    },
    hosting: {
      format: EVENT_FORMAT.VIRTUAL,
      address: {
        street: "",
        city: "Online",
        state: "",
        postal_code: "",
        country: "",
        vanue: "Virtual Stage",
        maps_link: "",
      },
      virtual_links: {
        meeting_url: "https://zoom.us/j/123456789"
      },
    },
    access_control: {
      require_rsvp: false,
      view_details: DETAIL_VIEW_MODE.BEFORE,
    },
    cancellation_policy: {
      allowed: false,
      refund_strategy: REFUND_STRATEGY.NONE,
      tiered_refunds: [],
    },
    terms_and_conditions: [],
  },
  {
    title: "Business Networking Mixer",
    description: "Connect with fellow entrepreneurs and business professionals in this exclusive networking event.",
    slug: "business-networking-mixer",
    avatar: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400",
    category: "business",
    images: [],
    tags: ["business", "networking", "professional", "mixer"],
    status: EVENT_STATUS.PUBLISHED,
    creator: "user-3",
    host: "user-3",
    property: "property-3",
    schedule: {
      mode: SCHEDULE_MODE.SINGLE,
      start_time: new Date("2024-05-25T18:00:00Z"),
      end_time: new Date("2024-05-25T21:00:00Z"),
      registration_start_time: new Date("2024-05-01T00:00:00Z"),
      registration_end_time: new Date("2024-05-24T23:59:59Z"),
      timezone: "America/Los_Angeles",
      recurrence: {
        pattern: RECURRENCE_PATTERN.DAILY,
        interval: 1,
        current_occurences: 0,
        max_occurences: 1,
      },
    },
    visibility: EVENT_VISIBILITY.PUBLIC,
    ticketing: {
      enabled: true,
      capacity: 150,
    },
    hosting: {
      format: EVENT_FORMAT.PHYSICAL,
      address: {
        street: "456 Business Ave",
        city: "New York",
        state: "NY",
        postal_code: "10001",
        country: "US",
        vanue: "Business Center",
        maps_link: "",
      },
      virtual_links: {},
    },
    access_control: {
      require_rsvp: true,
      view_details: DETAIL_VIEW_MODE.BEFORE,
    },
    cancellation_policy: {
      allowed: true,
      refund_strategy: REFUND_STRATEGY.FULL,
      tiered_refunds: [],
    },
    terms_and_conditions: ["Professional attire required"],
  },
  {
    title: "Art Workshop: Painting Basics",
    description: "Learn the fundamentals of painting in this hands-on workshop suitable for beginners.",
    slug: "art-workshop-painting-basics",
    avatar: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400",
    category: "arts",
    images: [],
    tags: ["art", "workshop", "painting", "beginner"],
    status: EVENT_STATUS.PUBLISHED,
    creator: "user-4",
    host: "user-4",
    property: "property-4",
    schedule: {
      mode: SCHEDULE_MODE.SINGLE,
      start_time: new Date("2024-06-08T14:00:00Z"),
      end_time: new Date("2024-06-08T17:00:00Z"),
      registration_start_time: new Date("2024-05-15T00:00:00Z"),
      registration_end_time: new Date("2024-06-07T23:59:59Z"),
      timezone: "America/Chicago",
      recurrence: {
        pattern: RECURRENCE_PATTERN.DAILY,
        interval: 1,
        current_occurences: 0,
        max_occurences: 1,
      },
    },
    visibility: EVENT_VISIBILITY.PUBLIC,
    ticketing: {
      enabled: true,
      capacity: 25,
    },
    hosting: {
      format: EVENT_FORMAT.PHYSICAL,
      address: {
        street: "789 Art Street",
        city: "Chicago",
        state: "IL",
        postal_code: "60601",
        country: "US",
        vanue: "Art Studio",
        maps_link: "",
      },
      virtual_links: {},
    },
    access_control: {
      require_rsvp: true,
      view_details: DETAIL_VIEW_MODE.BEFORE,
    },
    cancellation_policy: {
      allowed: true,
      refund_strategy: REFUND_STRATEGY.PARTIAL,
      refund_percentage: 50,
      tiered_refunds: [],
    },
    terms_and_conditions: ["Materials provided"],
  },
  {
    title: "Hybrid Health & Wellness Summit",
    description: "Join experts discussing the latest in health and wellness, available both in-person and online.",
    slug: "hybrid-health-wellness-summit",
    avatar: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    category: "health",
    images: [],
    tags: ["health", "wellness", "hybrid", "summit"],
    status: EVENT_STATUS.PUBLISHED,
    creator: "user-5",
    host: "user-5",
    property: "property-5",
    schedule: {
      mode: SCHEDULE_MODE.SINGLE,
      start_time: new Date("2024-08-10T10:00:00Z"),
      end_time: new Date("2024-08-10T16:00:00Z"),
      registration_start_time: new Date("2024-07-01T00:00:00Z"),
      registration_end_time: new Date("2024-08-09T23:59:59Z"),
      timezone: "America/Denver",
      recurrence: {
        pattern: RECURRENCE_PATTERN.DAILY,
        interval: 1,
        current_occurences: 0,
        max_occurences: 1,
      },
    },
    visibility: EVENT_VISIBILITY.PUBLIC,
    ticketing: {
      enabled: false,
      capacity: 300,
    },
    hosting: {
      format: EVENT_FORMAT.HYBRID,
      address: {
        street: "321 Wellness Blvd",
        city: "Denver",
        state: "CO",
        postal_code: "80202",
        country: "US",
        vanue: "Wellness Center",
        maps_link: "",
      },
      virtual_links: {
        meeting_url: "https://teams.microsoft.com/l/meetup-join/..."
      },
    },
    access_control: {
      require_rsvp: false,
      view_details: DETAIL_VIEW_MODE.BEFORE,
    },
    cancellation_policy: {
      allowed: false,
      refund_strategy: REFUND_STRATEGY.NONE,
      tiered_refunds: [],
    },
    terms_and_conditions: [],
  },
  {
    title: "Food & Wine Tasting",
    description: "Indulge in exquisite food and wine pairings curated by renowned chefs and sommeliers.",
    slug: "food-wine-tasting",
    avatar: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400",
    category: "food",
    images: [],
    tags: ["food", "wine", "tasting", "culinary"],
    status: EVENT_STATUS.PUBLISHED,
    creator: "user-6",
    host: "user-6",
    property: "property-6",
    schedule: {
      mode: SCHEDULE_MODE.SINGLE,
      start_time: new Date("2024-09-15T19:00:00Z"),
      end_time: new Date("2024-09-15T22:00:00Z"),
      registration_start_time: new Date("2024-08-01T00:00:00Z"),
      registration_end_time: new Date("2024-09-14T23:59:59Z"),
      timezone: "America/Los_Angeles",
      recurrence: {
        pattern: RECURRENCE_PATTERN.DAILY,
        interval: 1,
        current_occurences: 0,
        max_occurences: 1,
      },
    },
    visibility: EVENT_VISIBILITY.PUBLIC,
    ticketing: {
      enabled: true,
      capacity: 80,
    },
    hosting: {
      format: EVENT_FORMAT.PHYSICAL,
      address: {
        street: "555 Culinary Lane",
        city: "Los Angeles",
        state: "CA",
        postal_code: "90210",
        country: "US",
        vanue: "Fine Dining Restaurant",
        maps_link: "",
      },
      virtual_links: {},
    },
    access_control: {
      require_rsvp: true,
      view_details: DETAIL_VIEW_MODE.BEFORE,
    },
    cancellation_policy: {
      allowed: true,
      refund_strategy: REFUND_STRATEGY.TIERED,
      tiered_refunds: [
        {
          before_date: new Date("2024-09-10T00:00:00Z"),
          percentage: 100
        },
        {
          before_date: new Date("2024-09-13T00:00:00Z"),
          percentage: 50
        }
      ],
    },
    terms_and_conditions: ["Must be 21+ to attend"],
    sponsors: [
      { name: "Wine Co" },
      { name: "Gourmet Foods" }
    ],
  }
]